ServerConfig:
  host: localhost
  port: 8080
  
DatabaseConfig:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: partycalc

LoggerConfig:
  encoding: json
  level: info
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
  encoderConfig:
    messageKey: message
    levelKey: level
    timeKey: time
    timeEncoder: ISO8601
    levelEncoder: capital
    durationEncoder: string
    callerEncoder: short
