ServerConfig:
  host: localhost
  port: 8080
  
DatabaseConfig:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: partycalc

LoggerConfig:
  encoding: json
  level: 
    default: info
  outputPaths:
    - stdout
  errorOutputPaths:
    - stderr
  encoderConfig:
    messageKey: message
    levelKey: level
    timeKey: time
    encodeTime: ISO8601
    encodeLevel: capital
    encodeDuration: string
    encodeCaller: short
