version: '3'

services:
  #app:
  #  build: .
  #  ports:
  #   - "8080:8080"
  # depends_on:
  #   - db

  postgres-db:
    build: ./
    image: postgres:15
    ports: -5432:5432
    volumes: -./
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: partycalc

