CREATE TABLE IF NOT EXISTS persons (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
	Id SERIAL PRIMARY KEY,
	Name VARCHAR(30),
	Date DATE,
	Total NUMERIC
);

CREATE TABLE IF NOT EXISTS pers_events (
	Id SERIAL PRIMARY KEY,
	Person INT,
	Event INT,
	Spent NUMERIC,
	Factor INT,
	FOREIGN KEY (Person) REFERENCES persons(Id),
	FOREIGN KEY (Event) REFERENCES events(Id)
)